packages:
  - '.'

allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@astrojs/check@0.9.10'
  - astro@7.1.4
onlyBuiltDependencies:
  - esbuild
overrides:
  postcss: 8.5.23
  nanoid: 3.3.17
  js-yaml: 4.3.1
  fast-uri: 3.1.5
